/**
 * Environment module — loads a precomputed sky cube map.
 * No runtime WebGL/PMREM generation. The cube map faces are static
 * assets generated by scripts/generate-env-cubemap.cjs.
 */

import * as THREE from 'three';
import type { Texture } from 'three';
import { SUN_ELEVATION, SUN_AZIMUTH } from '../config';

export interface EnvironmentResult {
  environmentMap: Texture;
  sunDirection: THREE.Vector3;
  dispose: () => void;
}

/**
 * Load the precomputed sky cube map and compute sun direction.
 */
export function generateEnvironment(): EnvironmentResult {
  // Sun direction from config
  const phi = THREE.MathUtils.degToRad(90 - SUN_ELEVATION);
  const theta = THREE.MathUtils.degToRad(SUN_AZIMUTH);
  const sunDirection = new THREE.Vector3();
  sunDirection.setFromSphericalCoords(1, phi, theta);

  // Load static cube map
  const loader = new THREE.CubeTextureLoader();
  loader.setPath('/env/');
  const environmentMap = loader.load([
    'px.png', 'nx.png',
    'py.png', 'ny.png',
    'pz.png', 'nz.png',
  ]);

  console.log(`[environment] static cube map loaded (sun: elev=${SUN_ELEVATION}° az=${SUN_AZIMUTH}°)`);

  return {
    environmentMap,
    sunDirection,
    dispose: () => {
      environmentMap.dispose();
    },
  };
}
